sudo: false
language: node_js
node_js:
  - "10"
branches:
  only:
  - master
  - auth
cache:
  directories:
  - node_modules
install:
  - npm install
script:
  - npm run build
addons:
  ssh_known_hosts: 39.107.119.46 # 请替换成自己的服务器IP
before_deploy: 
  - openssl aes-256-cbc -K $encrypted_ed86006c7fbb_key -iv $encrypted_ed86006c7fbb_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/dist $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master