sudo: false
language: node_js
node_js:
  - 8
cache:
  directories:
  - node_modules
before_install: 
  - openssl aes-256-cbc -K $encrypted_383bc2ea2d21_key -iv $encrypted_383bc2ea2d21_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
script:
  - npm run build
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $deploy_user@39.107.119.46:$DEPLOY_PATH
  on:
    branch: master
addons:
  ssh_known_hosts: 39.107.119.46 # 请替换成自己的服务器IP